// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package source

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"clientID": {
			Default:     "",
			Description: "clientID is the client id from the salesforce app",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"clientSecret": {
			Default:     "",
			Description: "clientSecret is the client secret from the salesforce app",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"oauthEndpoint": {
			Default:     "",
			Description: "oauthEndpoint is the oauthEndpoint from the salesforce app",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"topicName": {
			Default:     "",
			Description: "topicName is the topic the source connector will subscribe to",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"username": {
			Default:     "",
			Description: "Deprecated: username is the client secret from the salesforce app.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
	}
}
