// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package oauth

import (
	"net/http"
	"sync"
)

// Ensure, that httpClientMock does implement httpClient.
// If this is not the case, regenerate this file with moq.
var _ httpClient = &httpClientMock{}

// httpClientMock is a mock implementation of httpClient.
//
// 	func TestSomethingThatUseshttpClient(t *testing.T) {
//
// 		// make and configure a mocked httpClient
// 		mockedhttpClient := &httpClientMock{
// 			DoFunc: func(req *http.Request) (*http.Response, error) {
// 				panic("mock out the Do method")
// 			},
// 		}
//
// 		// use mockedhttpClient in code that requires httpClient
// 		// and then make assertions.
//
// 	}
type httpClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(req *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Req is the req argument value.
			Req *http.Request
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *httpClientMock) Do(req *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("httpClientMock.DoFunc: method is nil but httpClient.Do was just called")
	}
	callInfo := struct {
		Req *http.Request
	}{
		Req: req,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(req)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//     len(mockedhttpClient.DoCalls())
func (mock *httpClientMock) DoCalls() []struct {
	Req *http.Request
} {
	var calls []struct {
		Req *http.Request
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
